version: '3'
services:
  nginx:
    container_name: nginx-container
    build:
      context: /home/{{ ansible_user }}/Desktop/docker_app
    ports:
      - "80:80"
    volumes:
      - /home/{{ ansible_user }}/Desktop/docker_app/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: php:7.4-fpm
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
