---
- name: Create directory on Desktop
  file:
    path: "/home/{{ ansible_user }}/Desktop/docker_app"
    state: directory

- name: Copy Nginx configuration file
  template:
    src: "templates/nginx.conf.j2"
    dest: "/home/{{ ansible_user }}/Desktop/docker_app/nginx.conf"
  notify:
    - Restart Nginx
