---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Create project docker directory
  file:
    path: /home/{{ ansible_user }}/test_task_ansible/docker
    state: directory
    mode: '0755'

- name: Copy project files
  copy:
    src: "{{ playbook_dir }}/../docker"
    dest: /home/{{ ansible_user }}/test_task_ansible/docker
    mode: '0755'

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/test_task_ansible/docker/docker-compose.yml

- name: Start Docker Compose
  command: docker-compose up -d
  args:
    chdir: /home/{{ ansible_user }}/test_task_ansible/docker
