---
- name: Copy Docker Compose file
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "/home/{{ ansible_user }}/Desktop/docker_app/docker-compose.yml"

- name: Copy Dockerfile
  copy:
    src: "../../../docker/Dockerfile"
    dest: "/home/{{ ansible_user }}/Desktop/docker_app/Dockerfile"

- name: Start Docker Compose
  command: docker-compose -f /home/{{ ansible_user }}/Desktop/docker_app/docker-compose.yml up -d

- name: Ensure nginx container is running
  docker_container:
    name: nginx-container
    state: started