---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/docker-compose.yml

- name: Start Docker Compose
  command: docker-compose up -d
  args:
    chdir: /home/{{ ansible_user }}
